Update img-rotate-fix-sort.py
Premature end of JPEG file
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 265
    261     continue
    263 img_h, img_w = img.shape[:2]
--> 265 pred_boxes = get_model_predictions(model, img_path)
    267 if REQUIRE_MODEL_DETECTIONS and len(pred_boxes) == 0:
    268     save_manual(img_path, label_path, split)

Cell In[1], line 145, in get_model_predictions(model, img_path)
    144 def get_model_predictions(model, img_path):
--> 145     result = model.predict(
    146         source=str(img_path),
    147         conf=CONF_THRES,
    148         verbose=False
    149     )[0]
    151     pred_boxes = []
    153     if result.boxes is None:

File /project/ai-for-trap-processing-now/test_venv/lib64/python3.9/site-packages/ultralytics/engine/model.py:560, in Model.predict(self, source, stream, predictor, **kwargs)
    558 if prompts and hasattr(self.predictor, "set_prompts"):  # for SAM-type models
    559     self.predictor.set_prompts(prompts)
--> 560 return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)

File /project/ai-for-trap-processing-now/test_venv/lib64/python3.9/site-packages/ultralytics/engine/predictor.py:175, in BasePredictor.__call__(self, source, model, stream, *args, **kwargs)
    173     return self.stream_inference(source, model, *args, **kwargs)
    174 else:
--> 175     return list(self.stream_inference(source, model, *args, **kwargs))

File /project/ai-for-trap-processing-now/test_venv/lib64/python3.9/site-packages/torch/utils/_contextlib.py:36, in _wrap_generator.<locals>.generator_context(*args, **kwargs)
     33 try:
     34     # Issuing `None` to a generator fires it up
     35     with ctx_factory():
---> 36         response = gen.send(None)
     38     while True:
     39         try:
     40             # Forward the response to our caller and get its next request

File /project/ai-for-trap-processing-now/test_venv/lib64/python3.9/site-packages/ultralytics/engine/predictor.py:257, in BasePredictor.stream_inference(self, source, model, *args, **kwargs)
    255 # Preprocess
    256 with profilers[0]:
--> 257     im = self.preprocess(im0s)
    259 # Inference
    260 with profilers[1]:

File /project/ai-for-trap-processing-now/test_venv/lib64/python3.9/site-packages/ultralytics/engine/predictor.py:127, in BasePredictor.preprocess(self, im)
    125 not_tensor = not isinstance(im, torch.Tensor)
    126 if not_tensor:
--> 127     im = np.stack(self.pre_transform(im))
    128     im = im[..., ::-1].transpose((0, 3, 1, 2))  # BGR to RGB, BHWC to BCHW, (n, 3, h, w)
    129     im = np.ascontiguousarray(im)  # contiguous

File /project/ai-for-trap-processing-now/test_venv/lib64/python3.9/site-packages/numpy/_core/shape_base.py:444, in stack(arrays, axis, out, dtype, casting)
    442 arrays = [asanyarray(arr) for arr in arrays]
    443 if not arrays:
--> 444     raise ValueError('need at least one array to stack')
    446 shapes = {arr.shape for arr in arrays}
    447 if len(shapes) != 1:

ValueError: need at least one array to stack