Update mini-model.py
Ultralytics 8.3.78 🚀 Python-3.9.21 torch-2.6.0+cu124 CUDA:0 (Tesla V100-SXM2-32GB, 32494MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=seed_good/data.yaml, epochs=50, time=None, patience=100, batch=4, imgsz=960, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=seed_orientation_checker, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=/project/ai-for-trap-processing-now/test_venv/runs/detect/seed_orientation_checker
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
File /project/ai-for-trap-processing-now/test_venv/lib64/python3.9/site-packages/ultralytics/engine/trainer.py:564, in BaseTrainer.get_dataset(self)
    558 elif self.args.data.split(".")[-1] in {"yaml", "yml"} or self.args.task in {
    559     "detect",
    560     "segment",
    561     "pose",
    562     "obb",
    563 }:
--> 564     data = check_det_dataset(self.args.data)
    565     if "yaml_file" in data:

File /project/ai-for-trap-processing-now/test_venv/lib64/python3.9/site-packages/ultralytics/data/utils.py:376, in check_det_dataset(dataset, autodownload)
    375     m += f"\nNote dataset download directory is '{DATASETS_DIR}'. You can update this in '{SETTINGS_FILE}'"
--> 376     raise FileNotFoundError(m)
    377 t = time.time()

FileNotFoundError: 
Dataset 'seed_good/data.yaml' images not found ⚠️, missing path '/project/ai-for-trap-processing-now/datasets/seed_good/images/val'
Note dataset download directory is '/project/ai-for-trap-processing-now/datasets'. You can update this in '/home/zachary.dawson/.config/Ultralytics/settings.json'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Cell In[4], line 5
      1 from ultralytics import YOLO
      3 model = YOLO("yolov8n.pt")
----> 5 model.train(
      6     data="seed_good/data.yaml",
      7     epochs=50,
      8     imgsz=960,
      9     batch=4,
     10     name="seed_orientation_checker"
     11 )

File /project/ai-for-trap-processing-now/test_venv/lib64/python3.9/site-packages/ultralytics/engine/model.py:804, in Model.train(self, trainer, **kwargs)
    801 if args.get("resume"):
    802     args["resume"] = self.ckpt_path
--> 804 self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
    805 if not args.get("resume"):  # manually set model only if not resuming
    806     self.trainer.model = self.trainer.get_model(weights=self.model if self.ckpt else None, cfg=self.model.yaml)

File /project/ai-for-trap-processing-now/test_venv/lib64/python3.9/site-packages/ultralytics/engine/trainer.py:134, in BaseTrainer.__init__(self, cfg, overrides, _callbacks)
    132 self.model = check_model_file_from_stem(self.args.model)  # add suffix, i.e. yolo11n -> yolo11n.pt
    133 with torch_distributed_zero_first(LOCAL_RANK):  # avoid auto-downloading dataset multiple times
--> 134     self.trainset, self.testset = self.get_dataset()
    135 self.ema = None
    137 # Optimization utils init

File /project/ai-for-trap-processing-now/test_venv/lib64/python3.9/site-packages/ultralytics/engine/trainer.py:568, in BaseTrainer.get_dataset(self)
    566             self.args.data = data["yaml_file"]  # for validating 'yolo train data=url.zip' usage
    567 except Exception as e:
--> 568     raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    569 self.data = data
    570 return data["train"], data.get("val") or data.get("test")

RuntimeError: Dataset 'seed_good/data.yaml' error ❌ 
Dataset 'seed_good/data.yaml' images not found ⚠️, missing path '/project/ai-for-trap-processing-now/datasets/seed_good/images/val'
Note dataset download directory is '/project/ai-for-trap-processing-now/datasets'. You can update this in '/home/zachary.dawson/.config/Ultralytics/settings.json'